import test from 'node:test';import assert from 'node:assert/strict';import {classify,randomThrow,evaluate,blessingIndex} from '../logic.js';
const h=(...k)=>k.map(kind=>({kind}));
test('all face combinations and anomalous throws',()=>{assert.equal(classify('flat','convex'),'holy');assert.equal(classify('convex','flat'),'holy');assert.equal(classify('flat','flat'),'laugh');assert.equal(classify('convex','convex'),'yin');assert.equal(classify('edge','flat'),'invalid');assert.equal(classify('outside','convex'),'invalid')});
test('one throw cannot silently reroll an unfavourable answer',()=>{assert.equal(evaluate('single',h('holy')).passed,true);assert.equal(evaluate('single',h('yin')).passed,false);assert.equal(evaluate('single',h('laugh')).done,true)});
test('majority waits for three and requires at least two holy results',()=>{for(let mask=0;mask<8;mask++){const vals=Array.from({length:3},(_,i)=>mask&(1<<i)?'holy':'yin');assert.equal(evaluate('majority',h(...vals.slice(0,2))).done,false);const p=evaluate('majority',h(...vals));assert.equal(p.done,true);assert.equal(p.passed,vals.filter(v=>v==='holy').length>=2)}});
test('three consecutive means consecutive, resets on laugh or yin',()=>{assert.equal(evaluate('streak',h('holy','holy','laugh','holy')).streak,1);assert.equal(evaluate('streak',h('holy','holy','yin','holy','holy')).passed,false);assert.equal(evaluate('streak',h('yin','holy','holy','holy')).passed,true)});
test('invalid throw ends every rule without fabricated approval',()=>{for(const r of ['single','majority','streak']){assert.equal(evaluate(r,h('invalid')).done,true);assert.equal(evaluate(r,h('invalid')).passed,false)}});
test('random face sampling produces matching classifications',()=>{const values=[.1,.3,.7];let i=0;assert.deepEqual(randomThrow(()=>values[i++]),{a:'flat',b:'convex',kind:'holy'});assert.equal(randomThrow(()=>0).kind,'invalid');assert.equal(randomThrow(()=>.015).a,'outside');for(let j=0;j<1000;j++){const r=randomThrow();assert.equal(r.kind,classify(r.a,r.b))}});
test('creative fortune mapping does not invent a passed ritual',()=>{assert.equal(blessingIndex('single',h('holy')),0);assert.equal(blessingIndex('single',h('laugh')),1);assert.equal(blessingIndex('single',h('yin')),2);assert.equal(blessingIndex('majority',h('holy','holy','yin')),1);assert.equal(blessingIndex('streak',h('holy','holy')),2)});
