import {tr,language,initI18n} from './i18n.js';
import {HandCamera} from './camera.js';
import {cameraFlow,pairLift} from './camera-flow.js';
import {RULES,OUTCOMES,BLESSINGS,TOPICS,randomThrow,evaluate,blessingIndex} from './logic.js';
const $=s=>document.querySelector(s),journey=$('#journey'),stage=$('#stage');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>new Intl.DateTimeFormat(language==='zh'?'zh-CN':'en',{month:'long',day:'numeric',weekday:'long'}).format(d);
let handCamera=null,liftAmount=0;
let phase='setup',rule='single',name='',topic='general',question=TOPICS.general.question,history=[],blessing=null,skin='red',epoch=0,clockId=null,soundOn=false,audioCtx=null,cardBlob=null,cardUrl=null,cardGeneration=0,sessionDate=new Date();
$('#today').textContent=dateLabel(sessionDate);
const atlas=new Image();atlas.onload=()=>document.body.classList.add('assets-ready');atlas.src='assets/moonblocks.png';
const brandImage=new Image();brandImage.src='assets/logo.png';
function announce(text){$('#announcement').textContent=text}
function tone(freq=380,duration=.13){if(!soundOn)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume().catch(()=>{});const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.45,audioCtx.currentTime+duration);g.gain.setValueAtTime(.10,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}catch{soundOn=false;updateSound()}}
function updateSound(){$('#sound').textContent=soundOn?'声 ON':'声 OFF';$('#sound').setAttribute('aria-pressed',soundOn);$('#sound').setAttribute('aria-label',soundOn?'关闭仪式音效':'开启仪式音效')}
$('#sound').onclick=()=>{soundOn=!soundOn;updateSound();if(soundOn)tone()};
function setFaces(a='flat',b='convex'){[a,b].forEach((f,i)=>{const el=$(i?'#blockB':'#blockA');el.className=`block block-${i?'right':'left'} ${f==='outside'?'convex':f}`;el.style.opacity=f==='outside'?'.08':'1';el.setAttribute('aria-label',faceText(f))});stage.setAttribute('aria-label',`筊杯落地：${faceText(a)}，${faceText(b)}`)}
function faceText(f){return {flat:'平面朝上 · 阳',convex:'凸面朝上 · 阴',edge:'一片立住',outside:'一片落出范围'}[f]}
function display(html){handCamera?.sync();updateCameraAction();journey.innerHTML=html;journey.classList.remove('fade-in');void journey.offsetWidth;journey.classList.add('fade-in');document.body.classList.toggle('journey-active',phase!=='setup');const focus=journey.querySelector('h2');if(focus){focus.tabIndex=-1;if(phase!=='setup')focus.focus({preventScroll:true})}}
function capture(){if(phase!=='setup')return;name=($('#nickname')?.value??name).trim().slice(0,20);question=$('#question')?.value.trim().slice(0,120)||question;const canonical=Object.values(TOPICS).find(t=>t.question===question||tr(t.question,'en')===question);if(canonical)question=canonical.question;topic=$('#topic')?.value||topic;rule=document.querySelector('[name=rule]:checked')?.value||rule}
function setup(){phase='setup';handCamera?.sync();clearInterval(clockId);epoch++;stage.classList.remove('tossing','landed','pair-armed');liftAmount=0;stage.style.setProperty('--pair-lift','0px');setFaces();$('#grannyWords').innerHTML='「小人已经打走啦，<br>唔使惊，好运会慢慢嚟。」';$('#stageCaption').textContent='双手合握，心里留一件事。';
 display(`<h2 class="panel-title">问一问，今天的好运。</h2><p class="helper">一次只问一件事，慢慢说，婆婆听着呢。</p><div class="field-row"><label class="field"><span class="field-label">你的称呼 <span class="optional">选填</span></span><input id="nickname" autocomplete="given-name" maxlength="20" placeholder="有缘人" value="${esc(name)}"></label><label class="field"><span class="field-label">祝福主题</span><select id="topic">${Object.entries(TOPICS).map(([k,t])=>`<option value="${k}" ${k===topic?'selected':''}>${t.label}</option>`).join('')}</select></label></div><label class="field"><span class="field-label">心里想问的事 <span class="optional">一次一件</span></span><textarea id="question" maxlength="120">${esc(tr(question))}</textarea></label><div class="rule-heading"><span>选择问法</span><button class="subtle-link" data-dialog="guide">怎么看筊？</button></div><fieldset class="rules"><legend class="sr-only">选择判定规则</legend>${Object.entries(RULES).map(([k,r])=>`<label class="rule-option"><input type="radio" name="rule" value="${k}" ${rule===k?'checked':''}><span><b>${r.label}</b><small>${r.detail}</small></span></label>`).join('')}</fieldset><button class="primary" id="begin">静心，开始问运 <span aria-hidden="true">↗</span></button><p class="input-note">称呼只用于这次祝福卡，不会上传。</p>`);
 $('#topic').onchange=()=>{topic=$('#topic').value;if($('#question'))$('#question').value=tr(TOPICS[topic].question)};$('#begin').onclick=()=>{capture();sessionDate=new Date();$('#today').textContent=dateLabel(sessionDate);history=[];blessing=null;phase='waiting';wait()};}
function wait(){tone(280,.3);const token=++epoch,deadline=Date.now()+10000;display(`<div class="status-body"><h2 class="panel-title">给心事，十秒钟。</h2><p class="helper">轻轻合掌，默念你想问的事。<br>把烦恼放下，给好运留一点空隙。</p><div class="countdown" id="countdown" aria-label="静候倒计时">10</div><p class="question-summary">${esc(question)}</p><button class="primary" id="readyBtn" disabled>静候片刻</button><button class="subtle-link" id="skipWait" style="margin-top:18px">已静心，跳过等待</button></div>`);$('#stageCaption').textContent='慢慢吸气，轻轻呼气。';$('#skipWait').onclick=ready;clearInterval(clockId);clockId=setInterval(()=>{if(token!==epoch)return clearInterval(clockId);const n=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('#countdown').textContent=n;if(!n)ready()},200);announce('静候十秒，心里默念一件事。')}
function ready(){clearInterval(clockId);epoch++;phase='ready';display(`<div class="status-body"><span class="eyebrow">${RULES[rule].label}</span><h2 class="panel-title" style="margin-top:15px">心意已到，可以掷筊了。</h2><p class="helper">想象双手把筊杯举到眉心，<br>轻轻抛起，让答案自然落地。</p><p class="camera-step">开启摄像头后，抬手再放下即可投掷。</p><p class="question-summary">${esc(question)}</p><button id="throw" class="primary">合掌，掷出筊杯 <span aria-hidden="true">↗</span></button><button id="restart" class="secondary">重新静心</button></div>`);$('#stageCaption').textContent='一掷一问，静待回应。';$('#throw').onclick=toss;$('#restart').onclick=setup;announce('静候完成，可以开始。');if(handCamera?.active)stage.scrollIntoView({behavior:'smooth',block:'center'})}
async function toss(source='button'){if(!canCast())return;if(phase==='setup'){capture();sessionDate=new Date();$('#today').textContent=dateLabel(sessionDate);history=[];blessing=null;}stage.style.setProperty('--throw-start',`${-liftAmount*65}px`);phase='tossing';stage.classList.remove('pair-armed');const token=++epoch,result=randomThrow();display(`<div class="status-body"><h2 class="panel-title">心意落地，好运将至。</h2><p class="helper">让筊杯自然落定。</p><div class="countdown">问</div><button class="primary" disabled>筊杯落定中…</button></div>`);stage.classList.remove('tossing','landed');void stage.offsetWidth;stage.classList.add('tossing');tone(480,.12);const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?180:1500;await new Promise(r=>setTimeout(r,duration));if(token!==epoch)return;stage.classList.add('landed');stage.classList.remove('tossing');liftAmount=0;stage.style.setProperty('--pair-lift','0px');tone(180,.18);history.push(result);setFaces(result.a,result.b);showOutcome();if(source==='gesture'){if(evaluate(rule,history).done){await new Promise(r=>setTimeout(r,1100));if(token!==epoch||phase!=='outcome')return;finishCup()}journey.scrollIntoView({behavior:'smooth',block:'start'})}}
function historyHtml(){return `<div class="history" aria-label="本轮投掷记录">${history.map((h,i)=>`<span class="${h.kind==='holy'?'holy':''}">第${i+1}次 ${OUTCOMES[h.kind].title}</span>`).join('')}</div>`}
function showOutcome(){phase='outcome';const last=history.at(-1),out=OUTCOMES[last.kind],p=evaluate(rule,history);let progress=last.kind==='invalid'?'本轮暂止，改天再问。':rule==='single'?(p.passed?'本轮已应允':'本轮未获应允'):rule==='majority'?`已掷 ${history.length} / 3 次，圣筊 ${p.holy} 次${p.done?` · ${p.passed?'本轮已应允':'本轮未获应允'}`:''}`:`连续圣筊 ${p.streak} / 3 次${p.passed?' · 本轮已应允':last.kind!=='holy'?'，连续次数已归零':''}`;display(`<div class="status-body"><span class="eyebrow">${RULES[rule].label}</span><h2 class="outcome-seal">${out.title}</h2><div class="face-labels"><span>${faceText(last.a)}</span><span>${faceText(last.b)}</span></div><p class="helper">${out.explanation}</p>${historyHtml()}<p class="round-status">${progress}</p><p class="question-summary">${esc(question)}</p><button id="next" class="primary">${p.done?'收下今日祝福':'合掌，再掷一次'} <span aria-hidden="true">↗</span></button>${!p.done?'<button id="stopRound" class="secondary">稍后再问，先收下婆婆的祝福</button>':''}<button class="subtle-link" data-dialog="guide" style="margin-top:18px">了解这个结果</button></div>`);$('#grannyWords').textContent=out.granny;$('#stageCaption').textContent=`${out.title} · ${last.kind==='holy'?'一平一凸':last.kind==='laugh'?'两片平面':last.kind==='yin'?'两片凸面':'暂不判定'}`;$('#next').onclick=p.done?finishCup:toss;if($('#stopRound'))$('#stopRound').onclick=finishCup;announce(`${out.title}。${out.explanation}${progress}`)}
function finishCup(){blessing=BLESSINGS[blessingIndex(rule,history)];showBlessing()}
function showBlessing(){phase='blessing';handCamera?.stop();const p=evaluate(rule,history);const interpretation=p.passed?'本轮筊象已应允':p.done?'本轮未获应允，婆婆仍把祝福送给你':'本轮尚未完成，先收下婆婆的祝福';display(`<div class="status-body"><span class="fortune-label">${esc(name||'有缘人')}的今日祝福</span><h2 class="outcome-seal">${blessing.name}</h2><p class="result-poem">${blessing.poem.replace('\n','<br>')}</p><p class="helper">${interpretation}</p><div class="reading"><b>${TOPICS[topic].label}</b><p>${blessing.meaning}</p></div><div class="reading"><b>今天，为自己做一件小事</b><p>${topic==='general'?blessing.action:TOPICS[topic].action}</p></div><div class="reading"><b>婆婆的叮咛</b><p>${blessing.reminder}</p></div><button id="makeCard" class="primary" style="margin-top:18px">把祝福存进相册 <span aria-hidden="true">↗</span></button><button id="again" class="secondary">再问一件心事</button><p class="input-note">好运签为创作祝福，不等同于传统筊象。</p></div>`);$('#makeCard').onclick=async()=>{$('#cardDialog').showModal();await makeCard()};$('#again').onclick=setup;$('#stageCaption').textContent='今日的福气，已经接住。';$('#grannyWords').textContent='「把福带走，记得好好照顾自己。」';announce(`你的今日祝福：${blessing.name}。${blessing.poem}`)}
const PUBLIC_URL='https://viviank0930.github.io/-/';
function entryUrl(){const host=location.hostname;return ['localhost','127.0.0.1',''].includes(host)||location.protocol==='file:'?PUBLIC_URL+'#start':location.origin+location.pathname+'#start'}
function buildQr(){const qr=window.qrcode(0,'M');qr.addData(entryUrl());qr.make();return qr}
function showQR(){try{const qr=buildQr();$('#qrImage').innerHTML=qr.createSvgTag({cellSize:5,margin:12,scalable:true});$('#qrHint').textContent='扫码即可打开游戏，无需登录。'}catch{$('#qrImage').textContent='二维码暂时不可用，请复制下方链接。'}$('#qr').showModal()}
async function copy(text){try{await navigator.clipboard.writeText(text);return true}catch{return false}}
$('#copyUrl').onclick=async()=>{const ok=await copy(entryUrl());$('#copyStatus').textContent=ok?'链接已复制。':`请长按复制：${entryUrl()}`};
document.addEventListener('click',e=>{const open=e.target.closest('[data-dialog]');if(open){const id=open.dataset.dialog;id==='qr'?showQR():$('#'+id).showModal()}const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close()});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function wrap(ctx,text,x,y,maxWidth,lineHeight){const paragraphs=text.split('\n');for(const paragraph of paragraphs){const tokens=language==='en'?paragraph.split(/(?<= )/):[...paragraph];let line='';for(const token of tokens){if(line&&ctx.measureText(line+token).width>maxWidth){ctx.fillText(line.trimEnd(),x,y);y+=lineHeight;line=token}else line+=token}if(line)ctx.fillText(line.trimEnd(),x,y);y+=lineHeight}return y}
async function makeCard(){if(!blessing)return;const generation=++cardGeneration;$('#downloadCard').disabled=true;$('#shareCard').disabled=true;$('#shareStatus').textContent='也可以长按图片，保存到相册。';const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1320;const ctx=canvas.getContext('2d'),colors={red:['#ffd4e4','#6b3046','#d5efbe'],ink:['#d7efc1','#27574f','#ffc9e0'],gold:['#fff0a6','#2d5684','#b9e7f0']}[skin];ctx.fillStyle=colors[0];ctx.fillRect(0,0,900,1320);ctx.fillStyle=colors[2];ctx.fillRect(0,0,900,145);ctx.fillRect(0,1165,900,155);ctx.fillRect(0,145,52,1020);ctx.fillRect(848,145,52,1020);ctx.strokeStyle=colors[1];ctx.globalAlpha=.4;ctx.lineWidth=2;ctx.strokeRect(34,34,832,1252);ctx.strokeRect(47,47,806,1226);ctx.globalAlpha=1;ctx.fillStyle=colors[1];ctx.font='20px sans-serif';ctx.textAlign='left';ctx.fillText('DAILY FORTUNE ORACLE',80,105);ctx.textAlign='right';ctx.fillText(new Intl.DateTimeFormat(language==='zh'?'zh-CN':'en').format(sessionDate),820,105);ctx.textAlign='center';ctx.font='25px sans-serif';ctx.fillText(tr(`${name||'有缘人'}的今日祝福`),450,215);ctx.font=language==='zh'?'150px "Songti SC", serif':'70px sans-serif';ctx.fillText(tr(blessing.name),450,405);ctx.font=language==='zh'?'43px "Songti SC", serif':'36px sans-serif';wrap(ctx,tr(blessing.poem),450,510,700,70);ctx.font='22px sans-serif';ctx.globalAlpha=.8;ctx.fillText(tr(TOPICS[topic].label),450,710);ctx.globalAlpha=1;ctx.font='26px sans-serif';wrap(ctx,tr(topic==='general'?blessing.action:TOPICS[topic].action),450,770,690,43);ctx.font='27px "Songti SC", serif';ctx.fillText(tr('「小人打走，好运留下。」'),450,940);try{const qr=buildQr(),n=qr.getModuleCount(),size=164,cell=size/n,x0=450-size/2,y0=993;ctx.fillStyle='#fff';ctx.fillRect(x0-13,y0-13,size+26,size+26);ctx.fillStyle='#24312c';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(qr.isDark(r,c))ctx.fillRect(x0+c*cell,y0+r*cell,Math.ceil(cell),Math.ceil(cell))}catch{}ctx.fillStyle=colors[1];ctx.font='19px sans-serif';ctx.fillText(tr('扫码接福 · 香港打小人数字祝福'),450,1210);ctx.font='16px sans-serif';ctx.globalAlpha=.7;ctx.fillText(tr('民俗互动体验，签文为创作祝福'),450,1245);const newBlob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(generation!==cardGeneration)return;cardBlob=newBlob;$('#downloadCard').disabled=false;$('#shareCard').disabled=false;if(!cardBlob){$('#shareStatus').textContent='图片暂未生成，请重试。';return}if(cardUrl)URL.revokeObjectURL(cardUrl);cardUrl=URL.createObjectURL(cardBlob);$('#cardPreview').src=cardUrl}
document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=async()=>{skin=b.dataset.skin;document.querySelectorAll('[data-skin]').forEach(el=>el.setAttribute('aria-pressed',el===b));await makeCard()});
$('#downloadCard').onclick=()=>{if(!cardUrl)return;const a=document.createElement('a');a.href=cardUrl;a.download=`Granny-Fortune-${tr(blessing.name)}-${sessionDate.getFullYear()}${sessionDate.getMonth()+1}${sessionDate.getDate()}.png`;a.click();$('#shareStatus').textContent='已发起保存；若手机未下载，可长按图片存入相册。'};
$('#shareCard').onclick=async()=>{if(!cardBlob)return;const file=new File([cardBlob],'今日祝福.png',{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:tr('婆婆送福'),text:tr('打走烦恼，把祝福带走。')});$('#shareStatus').textContent='分享完成。'}else{const ok=await copy(entryUrl());$('#shareStatus').textContent=ok?'链接已复制，可以连同保存的祝福卡一起分享。':`请保存图片，再分享此链接：${entryUrl()}`}}catch(e){$('#shareStatus').textContent=e.name==='AbortError'?'分享已取消，祝福卡仍可保存。':'暂时无法分享，可以先保存图片。'}};
initI18n((old,next)=>{const field=$('#question');if(field){const defaults=Object.values(TOPICS).map(t=>t.question);if(defaults.includes(field.value)||Object.values(TOPICS).some(t=>tr(t.question,'en')===field.value))field.value=tr(TOPICS[topic].question);else if(next==='zh'&&field.value===question)field.value=question;}$('#today').textContent=dateLabel(sessionDate);if($('#cardDialog').open)makeCard();});
function currentCameraFlow(){return cameraFlow({phase,done:phase==='outcome'&&evaluate(rule,history).done,dialog:!!document.querySelector('dialog[open]'),editing:['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)})}
function canCast(){return currentCameraFlow().enabled}
function updateCameraAction(){const action=currentCameraFlow().action,b=$('#cameraAction');if(!b)return;b.hidden=!action;b.textContent=action==='ready'?'已静心，准备掷筊':'查看本轮祝福';b.onclick=action==='ready'?ready:finishCup;}
function movePair({state,point,progress}){if(phase==='tossing')return;if(!canCast()||(!point&&stage.classList.contains('landed')))return;liftAmount=progress??pairLift(state,point);if(point)stage.classList.remove('landed');stage.style.setProperty('--pair-lift',`${-liftAmount*65}px`);stage.classList.toggle('pair-armed',state==='release');}

handCamera=new HandCamera({video:$('#handVideo'),canvas:$('#handOverlay'),button:$('#cameraToggle'),status:$('#cameraStatus'),canCast,onCast:()=>toss('gesture'),onMotion:movePair,pauseKey:()=>currentCameraFlow().key});
setup();if(location.hash==='#scan')showQR();
